# site1_handheld_1 80 score

common:
    lid_topic: "/rslidar_points"
    imu_topic: "/imu/data"
    con_frame: false # true: if you need to combine several LiDAR frames into one
    con_frame_num: 1 # the number of frames combined
    cut_frame: false # true: if you need to cut one LiDAR frame into several subframes
    cut_frame_time_interval: 0.1 # should be integral fraction of 1 / LiDAR frequency   
    time_diff_lidar_to_imu: 0.0 # Time offset between LiDAR and IMU calibrated by other algorithms, e.g., LI-Init (find in Readme)

preprocess:
    lidar_type: 4   # submit 4, visualize 5
    scan_line: 32
    timestamp_unit: 0           # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 1.0
    blind_for_human_pilot: 1.0
     
mapping:
    imu_en: true
    extrinsic_est_en: false # for aggressive motion, set this variable false
    imu_time_inte: 0.0025 # = 1 / frequency of IMU , for hilti IMU hz is 400
    satu_acc: 30.0 # the saturation value of IMU's acceleration. not related to the units
    satu_gyro: 35 # the saturation value of IMU's angular velocity. not related to the units
    acc_norm: 9.81 # 1.0 for g as unit, 9.81 for m/s^2 as unit of the IMU's acceleration
    lidar_meas_cov: 0.01 # 0.001
    acc_cov_output: 500
    gyr_cov_output: 1000 
    b_acc_cov: 0.0001 
    b_gyr_cov: 0.0001 
    imu_meas_acc_cov: 0.1 #0.1 # 2
    imu_meas_omg_cov: 0.1 #0.1 # 2 
    gyr_cov_input: 0.1 # for IMU as input model
    acc_cov_input: 0.1 # for IMU as input model
    plane_thr: 0.1 # 0.05, the threshold for plane criteria, the smaller, the flatter a plane
    match_s: 81


    fov_degree: 360 
    det_range: 120.0


    gravity: [0.0, 0.0, -9.810] # [-0.30, 0.880, -9.76] # liosam [0.0, 9.810, 0.0] # # preknown gravity, use when imu_en is false or start from a non-stationary state
    
    # extrinsic calibraiton
    extrinsic_T: [ 0.1337243509829615,  -0.01130179949804173, 0.01089303307797801]
    extrinsic_R: [ 0.9993809082422996, -0.003698810555961526, 0.03498741261178718, 
                  -0.003397272928783347, -0.9999566093030182, -0.0086739868491098,
                   0.03501797791768812, 0.008549755065630918, -0.9993501102771111]


publish:
    path_en: true                 # false: close the path output
    scan_publish_en: true         # false: close all the point cloud output
    scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

# For LiDAR odometry Saving
trajectory_save:
    traj_save_en: true
    traj_file_path: "/root/workspace/src/Point-LIO_hilti/trajectory/site2_robot_2.txt" # When you use docker, you should enter docker absolute path.
